export default {
  ADD_PARAGRAPH_HISTORY: 'ADD_PARAGRAPH_HISTORY',
  ADD_PARAGRAPH_HISTORY_NEXT_BY: 'ADD_PARAGRAPH_HISTORY_NEXT_BY',
  DELETE_PARAGRAPH_HISTORY: 'DELETE_PARAGRAPH_HISTORY',
  SET_MOOD: 'SET_MOOD',
  ADD_EMPTY_PARAGRAPH: 'ADD_EMPTY_PARAGRAPH',
  ADD_PARAGRAPH_WITH_CONFIRMED_CONTENT: 'ADD_PARAGRAPH_WITH_CONFIRMED_CONTENT',
  DELETE_PARAGRAPH: 'DELETE_PARAGRAPH'
}
