export default {
  ADD_PARAGRAPH_HISTORY: 'ADD_PARAGRAPH_HISTORY',
  ADD_PARAGRAPH_HISTORY_NEXT_BY: 'ADD_PARAGRAPH_HISTORY_NEXT_BY',
  DELETE_PARAGRAPH_HISTORY: 'DELETE_PARAGRAPH_HISTORY',
  SET_MOOD: 'SET_MOOD'
}
