export default {
  UPDATE_PARAGRAPH_HISTORIES: 'UPDATE_PARAGRAPH_HISTORIES',
  ADD_PARAGRAPH_HISTORY: 'ADD_PARAGRAPH_HISTORY',
  ADD_PARAGRAPH_HISTORY_NEXT_BY: 'ADD_PARAGRAPH_HISTORY_NEXT_BY',
  DELETE_PARAGRAPH_HISTORY: 'DELETE_PARAGRAPH_HISTORY',
  UPDATE_SUMMARY: 'UPDATE_SUMMARY',
  UPDATE_MOOD: 'UPDATE_MOOD',
  SET_MOOD: 'SET_MOOD',
  ADD_EMPTY_PARAGRAPH: 'ADD_EMPTY_PARAGRAPH',
  ADD_PARAGRAPH_WITH_CONFIRMED_CONTENT: 'ADD_PARAGRAPH_WITH_CONFIRMED_CONTENT',
  DELETE_PARAGRAPH: 'DELETE_PARAGRAPH',
  FOCUS_ON_SUMMARY_FALSE: 'FOCUS_ON_SUMMARY_FALSE',
  FOCUS_ON_SUMMARY_TRUE: 'FOCUS_ON_SUMMARY_TRUE',
  SET_FOCUS_TARGET: 'SET_FOCUS_TARGET',
  ADD_SUMMARY_INTO_SUMMARIES: 'ADD_SUMMARY_INTO_SUMMARIES',
  EDITING_IS_TRUE: 'EDITING_IS_TRUE',
  EDITING_IS_FALSE: 'EDITING_IS_FALSE'
}
